language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '12'
  - '11'
  - '10'
script:
  - yarn test:single
  - yarn build
after_success:
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
